version: V1.1.0
name: multi_i18n V1.1.0
description: |
    ## multi_i18n V1.1.0

    ### Added
    - Scan all YML files in the specified directories and generate a single source file from all YML sources