version: v1.0.0
name: multi_i18n v1.0.0
description: |
    ## multi_i18n v1.0.0
    - Support multi-language code generation
    - Only support C language code generation
    - Support Windows, Linux and macOS
    - Tested on Windows 10, macOS Sequoia 