# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Generator Manager Unit Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  Generator-Manager-Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Pytest generator manager
        run: |
          python3 -m pytest -v
