name: Build and Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Build project
        run: |
          pyinstaller multi_i18n.spec

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: multi_i18n
          path: dist/multi_i18n

  Release:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download production artifacts
        uses: actions/download-artifact@v3
        with:
          name: multi_i18n
          path: dist/multi_i18n

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: multi_i18n v1.0.0
          body: |
            ## multi_i18n v1.0.0
            - Support multi-language code generation
            - Only support C language code generation
            - Support Windows, Linux and macOS
            - Tested on Windows 10, macOS Sequoia 
          draft: false
          prerelease: false

      - name: Upload artifacts to GitHub Releases
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/
          asset_name: build-artifacts.zip
          asset_content_type: application/zip
